### PR TITLE
[cron] fixed a race

### LINKED ISSUE #107: Jobs are not triggered correctly in cron plugin
**Describe the bug**
We are running 4 jobs using the cron plugin @midnight and only the last job was running 3 times instead of on. After changing the scheduling to run the jobs with a 5 minutes gap, the last one was running at the time when the previous one should run and the at the time it should run.

image

https://werft.gitpod-dev.com/

More information can be found in the private issue https://github.com/gitpod-io/ops/issues/346

**To Reproduce**
Creating multiple jobs in the cron plugin should not work as expected.

**Expected behavior**
The jobs should run the time they are scheduled for.

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Fixes #107

### CODE REVIEW

File: plugins/cron/main.go [hunk 1]
```diff
@@ -60,16 +60,17 @@ func (*cronPlugin) Run(ctx context.Context, config interface{}, srv v1.WerftServ
...
-			_, err := srv.StartGitHubJob(ctx, &v1.StartGitHubJobRequest{
-				Metadata: &v1.JobMetadata{
-					Owner:       "cron",
-					Annotations: annotations,
-					Trigger:     trigger,
-					Repository:  repo,
-				},
-				JobPath: task.JobPath,
-			})
+			_, err := srv.StartGitHubJob(ctx, request)
```
Comment (csweichel) [inline plugins/cron/main.go:73]: Frankly I don't understand why solves the issue. Could you elaborate a bit on why this works?

Comment (JanKoehnlein) [reply plugins/cron/main.go:73]: The function that is passed as the second arg of `c.AddFunc()` is executed async. Then the loop has already finished and it gets the last value of  `task`. 
Maybe I am completely wrong but here's an example https://go.dev/play/p/HM7aueHpVQk

Comment (csweichel) [reply plugins/cron/main.go:73]: That makes a lot of sense. Thank you for the fix :)

**Review by csweichel — APPROVED** [review]
